image: node:latest
 
before_script:
 - npm install
 
cache:
 paths:
 - node_modules/
 
stages:
 - build

#Pre-production
build:
  type: build
  script:
    - npm run build
  only: 
    - develop
    - master