image: node:lastest
 
before_script:
 - npm install
 
cache:
 paths:
 - node_modules/
 
stages:
 - build

build:
  type: build
  script:
    - npm i && npm run build
  artifacts:
  paths:
    - build/