image: node:latest
 
# before_script:
#   - apt-get update -qy
#   - apt-get install -y ruby-dev
#   - gem install dpl
 
cache:
 paths:
 - node_modules/
 
stages:
 - build
 - docker
 - deploy

# #Pre-production
# build:
#   type: build
#   cache:
#     paths:
#       - dist/
#   script:
#     - npm install
#     - npm run build
#   only: 
#     - develop
#     - master

#Production
deploy:
  type: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=lionnel-patrick --api-key=$HEROKU_PRODUCTION_API_KEY
  only: 
    - master